import { INodeProperties } from 'n8n-workflow';

import {
	subscribeFields,
	unsubscribeFields,
	authFields,
	updateSubscriberFields,
	getSubscriberFields,
	searchSubscriberFields,
	createTagFields,
	updateTagFields,
	getTagFields,
	deleteTagFields,
	getSubscriptionProcessFields,
	getSubscriptionProcessRedirectionUrlFields,
	deleteSubscriberFields,
	tagEmailFields,
	untagEmailFields,
	signInFields,
	signOffFields,
	signOutFields,
	resendAutoresponderFields,
	getSubscribersByTagIdFields,
} from './fields';

import {
	createTag,
	getTag,
	fetchTags,
	updateTag,
	deleteTag,
	login,
	logout,
	signIn,
	signOut,
	signOff,
	subscribe,
	searchSubscriber,
	getSubscriptionProcessRedirectionUrl,
	deleteSubscriber,
	fetchSubscribers,
	unsubscribe,
	tagEmail,
	untagEmail,
	fetchContactFields,
	getSubscribersByTagId,
	fetchSubscriptionProcesses,
	getSubscriber,
	getSubscriptionProcess,
	resendAutoresponder,
	updateSubscriber,
} from './operation-options';

export const klickTippOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		options: [
			createTag,
			getTag,
			fetchTags,
			updateTag,
			deleteTag,
			login,
			logout,
			signIn,
			signOut,
			signOff,
			subscribe,
			searchSubscriber,
			getSubscriptionProcessRedirectionUrl,
			deleteSubscriber,
			fetchSubscribers,
			unsubscribe,
			tagEmail,
			untagEmail,
			fetchContactFields,
			getSubscribersByTagId,
			fetchSubscriptionProcesses,
			getSubscriber,
			getSubscriptionProcess,
			resendAutoresponder,
			updateSubscriber,
		],
		default: 'login',
	},
];

export const klickTippFields: INodeProperties[] = [
	...authFields,
	...createTagFields,
	...updateTagFields,
	...getTagFields,
	...deleteTagFields,
	...getSubscriberFields,
	...searchSubscriberFields,
	...subscribeFields,
	...tagEmailFields,
	...untagEmailFields,
	...unsubscribeFields,
	...updateSubscriberFields,
	...deleteSubscriberFields,
	...getSubscriptionProcessFields,
	...getSubscriptionProcessRedirectionUrlFields,
	...signInFields,
	...signOffFields,
	...signOutFields,
	...resendAutoresponderFields,
	...getSubscribersByTagIdFields,
];
